[externals]
## The external libs are libs which donot built/cloned by the tool
mkl = { path = "/opt/intel/mkl", exports = ["mkl_rt"],lib = "lib/intel64",include="include"}

#[tests]
#src   = ["deps/r2/src/logging.cc","tests/*.cc","src/stores/*.cc"]
#extra = ["rocksdb","mkl_rt","boost_serialization","jemalloc"]
#deps  = ["boost","ralloc"] ## cmake depends list

[installs]
boost = {url = "https://sourceforge.net/projects/boost/files/boost/1.61.0/boost_1_61_0.tar.gz", configure_cmd = "./bootstrap.sh  --with-libraries=system,coroutine,serialization", build_cmd = "./b2",install_cmd = "./b2 install",exports=["boost_system","boost_coroutine","boost_serialization"],include="include",lib="lib"}
#r2 = {url="https://ipads.se.sjtu.edu.cn:1312/weixd/r2.git",exports=[],include=".",build = false}
r2 = {url="https://github.com/wxdwfc/r2.git",exports=[],include=".",build = false}
tiny-dnn = {url = "https://github.com/tiny-dnn/tiny-dnn.git", exports=[], include=".", build=false}
kvs-workload = {url = "https://ipads.se.sjtu.edu.cn:1312/weixd/kvsworkloads.git", exports=[], include=".", build=false}
#rlib = {url="https://ipads.se.sjtu.edu.cn:1312/weixd/rib.git",build = false,exports=[],include=".."}
rlib = {url = "https://github.com/wxdwfc/rlibv2.git", build=false, exports=[],include=".."}
jemalloc={url="https://github.com/jemalloc/jemalloc.git",configure_cmd = "./configure --with-jemalloc-prefix=je",build_cmd = "make -j12",install_cmd = "",exports=["jemalloc"],include="include",build=true,lib="lib"}
libtorch={include="include/torch/csrc/api/include/",include2="include",build=false,package="Torch",exports=[]}

[includes]
## cmake add subdirectory
ggflags = {url = "https://github.com/gflags/gflags.git",include="include"}

[downloads]
## just downloads the specific libraries
cpptoml =  {url = "https://github.com/skystrife/cpptoml.git" }

[config]
std = "c++17"
#CMAKE_SHARED_LINKER_FLAGS="-Wl,--as-needed"


[[apps]]
name = "rw_client"
src = ["./benchs/bench_basic_rw.cc", "./deps/r2/src/logging.cc", "./deps/r2/src/sshed.cc"]
extra = ["boost_system","boost_coroutine", "pthread","gflags","ibverbs"]

[[apps]]
name = "bench_insert"
src = ["./benchs/bench_insert.cc", "./deps/r2/src/logging.cc"]
extra = ["pthread","gflags"]


[[apps]]
name = "rw_server"
src = ["./benchs/basic_rw_server.cc", "./deps/r2/src/logging.cc"]
extra = ["gflags","ibverbs","pthread"]

[[apps]]
name = "ycsb_server"
src = ["./benchs/ycsb/server/main.cc", "./deps/r2/src/logging.cc", "./benchs/terminate.cc" ]
extra = ["gflags","ibverbs","pthread","mkl_rt","boost_system", "boost_coroutine", "pthread"]

[[apps]]
name = "ycsb_client"
src = ["./benchs/ycsb/client.cc", "./deps/r2/src/logging.cc","./deps/r2/src/sshed.cc", "./benchs/terminate.cc"]
extra = ["gflags","ibverbs","pthread","mkl_rt","boost_system", "boost_coroutine", "pthread"]

#########################################################################################################################
# [[apps]]                                                                                                              #
# name = "ycsbd_server"                                                                                                 #
# src = ["./benchs/ycsbd/server/main.cc", "./deps/r2/src/logging.cc","./deps/r2/src/sshed.cc", "./benchs/terminate.cc"] #
# extra = ["gflags","ibverbs","pthread","mkl_rt","boost_system", "boost_coroutine", "pthread","jemalloc"]               #
#                                                                                                                       #
# [[apps]]                                                                                                              #
# name = "ycsbd_client"                                                                                                 #
# src = ["./benchs/ycsbd/client.cc", "./deps/r2/src/logging.cc","./deps/r2/src/sshed.cc", "./benchs/terminate.cc"]      #
# extra = ["gflags","ibverbs","pthread","mkl_rt","boost_system", "boost_coroutine", "pthread"]                          #
#########################################################################################################################

[[apps]]
name = "data_server"
src = ["./benchs/data_dist/server/main.cc", "./deps/r2/src/logging.cc","./deps/r2/src/sshed.cc", "./benchs/terminate.cc"]
extra = ["ibverbs","pthread","mkl_rt","boost_system", "boost_coroutine", "pthread","jemalloc","${TORCH_LIBRARIES}","gflags"]

## bench nn predict latency
[[apps]]
name = "bench_nn"
src = ["./benchs/data_dist/bench_nn.cc", "./deps/r2/src/logging.cc","./deps/r2/src/sshed.cc", "./benchs/terminate.cc"]
extra = ["ibverbs","pthread","mkl_rt","boost_system", "boost_coroutine", "pthread","jemalloc","${TORCH_LIBRARIES}","gflags"]


[[apps]]
name = "data_client"
src = ["./benchs/data_dist/client.cc", "./deps/r2/src/logging.cc","./deps/r2/src/sshed.cc", "./benchs/terminate.cc"]
extra = ["gflags","ibverbs","pthread","mkl_rt","boost_system", "boost_coroutine", "pthread","${TORCH_LIBRARIES}"]



########################################################################################
# ## unit tests                                                                        #
# [[apps]]                                                                             #
# name = "test_reg"                                                                    #
# src = ["./tests/test_reg.cc", "./deps/r2/src/logging.cc"]                            #
# extra = ["gflags","pthread","mkl_rt", "pthread", "jemalloc", "gtest"]                #
#                                                                                      #
# [[apps]]                                                                             #
# name = "test_snapshot"                                                               #
# src = ["./tests/test_snapshot.cc", "./deps/r2/src/logging.cc"]                       #
# extra = ["gflags","pthread","mkl_rt", "pthread", "jemalloc", "gtest","boost_system"] #
########################################################################################
